apiVersion: appprotect.f5.com/v1beta1
kind: APLogConf
metadata:
  name: logconf
spec:
  filter:
    request_type: all
  content:
    format: user-defined
    max_message_size: 64k
    max_request_size: any
    format_string: '{ ##logtype##: ##securitylog##, ##attack_type##: ##%attack_type%##, ##blocking_exception_reason##: ##%blocking_exception_reason%##, ##bot_anomalies##: ##%bot_anomalies%##, ##bot_category##: ##%bot_category%##, ##bot_signature_name##: ##%bot_signature_name%##, ##client_class##: ##%client_class%##, ##date_time##: ##%date_time%##, ##dest_port##: ##%dest_port%##, ##enforced_bot_anomalies##: ##%enforced_bot_anomalies%##, ##ip_client##: ##%ip_client%##, ##is_truncated_bool##: ##%is_truncated_bool%##, ##method##: ##%method%##, ##outcome##: ##%outcome%##, ##outcome_reason##: ##%outcome_reason%##, ##policy_name##: ##%policy_name%##, ##protocol##: ##%protocol%##, ##headers##: ##%headers%##, ##request_status##: ##%request_status%##, ##response_code##: ##%response_code%##, ##severity##: ##%severity%##, ##sig_cves##: ##%sig_cves%##, ##sig_ids##: ##%sig_ids%##, ##sig_names##: ##%sig_names%##, ##sig_set_names##: ##%sig_set_names%##, ##src_port##: ##%src_port%##, ##sub_violations##: ##%sub_violations%##, ##support_id##: ##%support_id%##, ##threat_campaign_names##: ##%threat_campaign_names%##, ##unit_hostname##: ##%unit_hostname%##, ##uri##: ##%uri%##, ##violation_rating##: ##%violation_rating%##, ##violations##: ##%violations%##, ##vs_name##: ##%vs_name%##, ##x_forwarded_for_header_value##: ##%x_forwarded_for_header_value%## }'


