apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: waf-policy
spec:
  waf:
    enable: true
    apPolicy: "staging/simple-ap"
    securityLog:
      enable: true
      apLogConf: "staging/logconf"
      logDest: "stderr"


